apiVersion: v1alpha1
kind: rule
meta:
  name: IsAgentsInstalledInVMs
  purpose: Is Agents Installed In VMs
  description: Is Agents Installed In VMs
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: IsAgentInstalledInVMs  
    alias: t1
    type: task
    purpose: IsAgentInstalledInVMs 
    description: IsAgentInstalledInVMs
  ioMap:
  - 't1.Input.VMsExtensionsDataFilePath:=*.Input.VMsExtensionsDataFilePath'
  - 't1.Input.ControlConfigFilePath:=*.Input.ControlConfigFilePath'
  - 't1.Input.ControlName:=*.Input.ControlName'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AgentInstalledInVMs:=t1.Output.AgentInstalledInVMs'
  - '*.Output.LogFile:=t1.Output.LogFile'
