apiVersion: v1alpha1
kind: rule
meta:
  name: AWSAccountAuthorizationDetails
  purpose: Fetch AWS Account Authorization Details
  description: Fetch AWS Account Authorization Details
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  tasks:
  - name: AWSAccountAuthorizationDetails
    alias: t1
    type: task 
    purpose: Fetch AWS Account Authorization Details
    description: Fetch AWS Account Authorization Details
  ioMap:
  - '*.Output.AccountAuthorizationDetails:=t1.Output.AccountAuthorizationDetails'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
