apiVersion: v1alpha1
kind: rule
meta:
  name: IsDiagnosticLogsEnabledInAzureServiceBus
  purpose: Is Diagnostic Logs Enabled In Azure ServiceBus
  description: Is Diagnostic Logs Enabled In Azure ServiceBus
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: IsDiagnosticLogsEnabledInServiceBus  
    alias: t1
    type: task
    purpose: IsDiagnosticLogsEnabledInServiceBus
    description: IsDiagnosticLogsEnabledInServiceBus
  ioMap:
  - 't1.Input.ServiceBusDiagnosticSettingsDataFilePath:=*.Input.ServiceBusDiagnosticSettingsDataFilePath'
  - '*.Output.DiagnosticLogsInServiceBusNameSpace:=t1.Output.DiagnosticLogsInServiceBusNameSpace'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
