apiVersion: v1alpha1
kind: rule
meta:
  name: AzureLogAnalyticsWkSpaceRetentionPeriodReport
  purpose: Azure Log Analytics WorkSpace Retention Period Report
  description: Azure Log Analytics WorkSpace Retention Period Report
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: AzureLogAnalyticsWkSpaceRetentionPeriodReport
    alias: t1
    type: task
    purpose: Azure Log Analytics WorkSpace Retention Period Report
    description: Azure Log Analytics WorkSpace Retention Period Report
  ioMap:
  - 't1.Input.AzureLogAnalyticsWorkSpaceData:=*.Input.AzureLogAnalyticsWorkSpaceData'
  - 't1.Input.RetentionInDays:=*.Input.RetentionInDays'
  - '*.Output.LogAnalyticsWkSpaceRetentionPeriodReport:=t1.Output.LogAnalyticsWkSpaceRetentionPeriodReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
