apiVersion: v1alpha1
kind: rule
meta:
  name: AWSAccessKeyRotationReport
  purpose: Generate a compliance report of AWS user access keys based on the provided AccessKeyAge.
  description: Standardization information related to the rotation of AWS access keys
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  tasks:
  - name: AWSAccessKeyRotationReport
    alias: t1
    type: task
    purpose: Generate a compliance report of AWS user access keys based on the provided AccessKeyAge.
    description: Standardization information related to the rotation of AWS access keys
  ioMap:
  - 't1.Input.MaxAccessKeyAge:=*.Input.MaxAccessKeyAge'
  - 't1.Input.AWSCredentialReport:=*.Input.AWSCredentialReport'
  - '*.Output.AccessKeyRotationReport:=t1.Output.AccessKeyRotationReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
