apiVersion: v1alpha1
kind: rule
meta:
  name: AWSEFSEncryptionReport
  purpose: Generate AWS EFS encryption report attached to the K8s cluster volume
  description: Generate AWS EFS encryption report attached to the K8s cluster volume
  labels:
    appType:
    - kubernetes
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - kubernetes
spec:
  tasks:
  - name: KubernetesPVList
    alias: t1
    type: task
    purpose: List K8s Persistent volume List
    description: List K8s Persistent volume List
  - name: AWSEFSList
    alias: t2
    type: task
    purpose: List AWS EFS List
    description: List AWS EFS List
  - name: AWSEFSEncryptionReport
    alias: t3
    type: task
    purpose: Generate AWS EFS encryption report attached to the K8s cluster volume
    description: Generate AWS EFS encryption report attached to the K8s cluster volume
  ioMap:
  - t1.Input.IncludeCriteria:=*.Input.IncludeCriteria
  - t1.Input.ExcludeCriteria:=*.Input.ExcludeCriteria
  - t2.Input.KubernetesPVList:=t1.Output.KubernetesPVList
  - t2.Input.KubernetesPVListLogFile:=t1.Output.KubernetesPVListLogFile
  - t2.Input.Region:=*.Input.Region
  - t3.Input.KubernetesPVListLogFile:=t2.Output.KubernetesPVListLogFile
  - t3.Input.AWSEFSListLogFile:=t2.Output.AWSEFSListLogFile
  - t3.Input.KubernetesPVList:=t1.Output.KubernetesPVList
  - t3.Input.AWSEFSList:=t2.Output.AWSEFSList
  - '*.Output.KubernetesPVList:=t1.Output.KubernetesPVList'
  - '*.Output.AWSEFSList:=t2.Output.AWSEFSList'
  - '*.Output.AWSEFSEncryptionReport:=t3.Output.AWSEFSEncryptionReport'
  - '*.Output.AWSEFSEncryptionReportLogFile:=t3.Output.AWSEFSEncryptionReportLogFile'
  - '*.Output.KubernetesPVListLogFile:=t3.Output.KubernetesPVListLogFile'
  - '*.Output.AWSEFSListLogFile:=t3.Output.AWSEFSListLogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_' 
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_' 