apiVersion: v1alpha1
kind: rule
meta:
  name: StandardizeAzureDefenderReport
  purpose: StandardizeAzureDefenderReport
  description: StandardizeAzureDefenderReport
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: StandardizeAzureDefenderReportTask
    alias: t1
    type: task
    purpose: StandardizeAzureDefenderReportTask
    description: StandardizeAzureDefenderReportTask
  ioMap:
  - 't1.Input.RuleDisplayName:=*.Input.RuleDisplayName'
  - 't1.Input.RuleConfig:=*.Input.RuleConfig'
  - 't1.Input.AzureReportData:=*.Input.AzureReportData'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AzureDefenderReport:=t1.Output.AzureDefenderReport'
  - '*.Output.LogFile:=t1.Output.LogFile'