userObject:
  app:
    name: NoCredApp
    appURL: http://localhost.com
    appPort: "0"
    userDefinedCredentials:
      NoCred:
        Dummy: ""
userInputs:
  HarFile: <<MINIO_FILE_PATH>>
fromDate: 2024-06-24
toDate: 2024-06-24
