apiVersion: v1alpha1
kind: rule
meta:
  name: AWSCredentialReport
  purpose: This report is used for various use case validations (e.g., user MFA check)
  description: The report includes a list of IAM users along with information such as their username, ARN (Amazon Resource Name), creation date, password last used date, and whether they have MFA enabled.
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  tasks:
  - name: AWSCredentialReport
    alias: t1
    type: task
    purpose: This report is used for various use case validations (e.g., user MFA check)
    description: The report includes a list of IAM users along with information such as their username, ARN (Amazon Resource Name), creation date, password last used date, and whether they have MFA enabled.
  ioMap:
  - '*.Output.AWSCredentialReport:=t1.Output.AWSCredentialReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_' 
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'  
