userObject:
  app:
    name: AzureAppConnector
    appURL: http://localhost.com
    appPort: "0"
    userDefinedCredentials:
      Azure:
        clientID: "$AZURE_CLIENT_ID"
        clientSecret: "$AZURE_CLIENT_SECRET"
        tenantID: "$AZURE_TENANT_ID"
        subscriptionID: "$AZURE_SUBSCRIPTION_ID"
userInputs:
  AzureRoleAssignmentsData: <<MINIO_FILE_PATH>>
  AzureUsersList: <<MINIO_FILE_PATH>>
  AzureStorageAccountsData: <<MINIO_FILE_PATH>>
  BackupStorageRegexPattern: backup
fromDate: 2024-07-02
toDate: 2024-07-02
