apiVersion: v1alpha1
kind: rule
meta:
  name: ProcessFindingsFromSecurityHub
  purpose: Process Findings From AWS SecurityHub
  description: Process Findings From AWS SecurityHub
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  tasks:
  - name: ProcessSecurityHubFindings
    alias: t1
    type: task
    purpose: Process SecurityHub Findings
    description: Process SecurityHub Findings
  ioMap:  
  - 't1.Input.SecurityHubFindingsFile:=*.Input.SecurityHubFindingsFile'
  - 't1.Input.ControlName:=*.Input.ControlName'
  - 't1.Input.ControlConfigFile:=*.Input.ControlConfigFile'
  - '*.Output.SecurityHubReport:=t1.Output.SecurityHubReport' 
  - '*.Output.SecurityHubFieldMeta:=t1.Output.SecurityHubFieldMeta'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
