authors:
- sangavi.l@continube.com
domain: continube
createdDate: 01/03/2024
name: CheckAWSDBInstanceBackup
displayName: Checks if RDS DB instances have backups enabled
version: '1.0'
description: Check AWS DB Instance Backup
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: MinimumRequiredRetentionPeriod
  description: MinimumRequiredRetentionPeriod
  type: int
  allowedValues: []
  defaultValue: ''
  showField: true
  isRequired: true
- name: RDSDBInstancesList
  description: RDSDBInstancesList
  type: string
  allowedValues: []
  defaultValue: ''
  showField: true
  isRequired: true  
outputs:
- name: DBInstanceBackupEnabled
  description: DB Instance Backup Enabled
  type: string
- name: LogFile
  description: Log File
  type: string
- name: CompliancePCT_
  description: Compliance Percentage
  type: int
- name: ComplianceStatus_
  description: Compliance Status
  type: string
