userObject:
  app:
    name: AWSAppConnector
    appURL: https://aws.amazon.com
    appPort: "0"
    userDefinedCredentials:
      AWSRole:
        AccessKey: "$AWS_ROLE_ACCESS_KEY"
        SecretKey: "$AWS_ROLE_SECRET_KEY"
        RoleARN: "$AWS_ROLE_ARN"
      AWSIAM:
        AccessKey: "$AWS_ACCESS_KEY"
        SecretKey: "$AWS_SECRET_KEY"
userInputs:
  MinimumRequiredRetentionPeriod: 
  RDSDBInstancesList: <<MINIO_FILE_PATH>>
  LogFile: <<MINIO_FILE_PATH>>
fromDate: 2024-03-01
toDate: 2024-03-01
