apiVersion: v1alpha1
kind: rule
meta:
  name: AzureVirtualMachinesData
  purpose: AzureVirtualMachinesData
  description: AzureVirtualMachinesData
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: GetAzureVirtualMachinesData
    alias: t1
    type: task
    purpose: GetAzureVirtualMachinesData
    description: GetAzureVirtualMachinesData
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AzureVirtualMachinesData:=t1.Output.AzureVirtualMachinesData'
  - '*.Output.AzureVirtualMachinesExtensionsData:=t1.Output.AzureVirtualMachinesExtensionsData'
  - '*.Output.LogFile:=t1.Output.LogFile'
