apiVersion: v1alpha1
kind: rule
meta:
  name: VerifyDBRetentionPeriod
  purpose: Verify DB Retention Period
  description: Verify DB Retention Period
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  tasks:
  - name: AWSRDSDBInstancesList
    alias: t1
    type: task
    purpose: Fetch the AWS RDS DB instances
    description: Fetch the AWS RDS DB instances
  - name: CheckAWSDBInstanceBackup
    alias: t2
    type: task
    purpose: Checks if RDS DB instances have backups enabled
    description: Checks if RDS DB instances have backups enabled
  ioMap:
  - 't1.Input.Region:=*.Input.Region'
  - 't2.Input.MinimumRequiredRetentionPeriod:=*.Input.MinimumRequiredRetentionPeriod'
  - 't2.Input.RDSDBInstancesList:=t1.Output.RDSDBInstancesList'
  - 't2.Input.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t2.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t2.Output.ComplianceStatus_'
  - '*.Output.DBInstanceBackupEnabled:=t2.Output.DBInstanceBackupEnabled'
  - '*.Output.LogFile:=t2.Output.LogFile'