authors:
- sangavi.l@continube.com
domain: continube
createdDate: 05/07/2024
name: JSVulsCheckUsingSemgrep
displayName: JSVulsCheckUsingSemgrep
version: '1.0'
description: JSVulsCheckUsingSemgrep
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: HarFile # A unique identifier of the task input
  description: HarFile # A concise description of the task input
  type: file # data type of the input. Available Types STRING, INT, FLOAT, FILE
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue:  # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  isRequired: true # boolean: true | false
outputs:
- name: StdSemgrepVulsReport
  description: StdSemgrepVulsReport
  type: file
- name: SemgrepVulsReport
  description: SemgrepVulsReport
  type: file
- name: LogFile
  description: LogFile
  type: file    
- name: ComplianceStatus_
  description: compliance status of the task
  type: string
- name: CompliancePCT_
  description: compliance percentage of the task
  type: int
