apiVersion: v1alpha1
kind: rule
meta:
  name: FetchSecurityHubFindings
  purpose: Fetch SecurityHub Findings
  description: Fetch SecurityHub Findings
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  tasks:
  - name: FetchSecurityHubFindings
    alias: t1
    type: task
    purpose: Fetch SecurityHub Findings
    description: Fetch SecurityHub Findings
  ioMap:
  - 't1.Input.Region:=*.Input.Region'
  - 't1.Input.AWSProductName:=*.Input.AWSProductName'
  - 't1.Input.FindingsRecordState:=*.Input.FindingsRecordState'
  - '*.Output.SecurityHubFindingsFile:=t1.Output.SecurityHubFindingsFile'
  - '*.Output.LogFile:=t1.Output.LogFile' 
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
