apiVersion: v1alpha1
kind: rule
meta:
  name: VerifySubresourceIntegrity
  purpose: Verify Subresource Integrity
  description: Verify the integrity of third-party resources such as CDNs and ensure they have not been manipulated or changed.
  labels:
    appType:
    - nocredapp
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - nocredapp
spec:
  tasks:
  - name: VerifySubresourceIntegrity
    alias: t1
    type: task
    purpose: Verify Subresource Integrity
    description: Verify the integrity of third-party resources such as CDNs and ensure they have not been manipulated or changed.
  ioMap:
  - 't1.Input.HARFile:=*.Input.HARFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.URIsWithSRIDetails:=t1.Output.URIsWithSRIDetails'
  - '*.Output.LogFile:=t1.Output.LogFile'
