apiVersion: v1alpha1
kind: rule
meta:
  name: JSVulsCheckUsingSemgrep
  purpose: Perform vulnerability scanning on JavaScript/TypeScript files using Semgrep 
  description: Perform vulnerability scanning on JavaScript/TypeScript files using Semgrep
  labels:
    appType:
    - nocredapp
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - nocredapp
spec:
  tasks:
  - name: JSVulsCheckUsingSemgrep
    alias: t1
    type: task
    purpose: Perform vulnerability scanning on JavaScript/TypeScript files using Semgrep
    description: Perform vulnerability scanning on JavaScript/TypeScript files using Semgrep
  ioMap:
  - 't1.Input.HarFile:=*.Input.HarFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.StdSemgrepVulsReport:=t1.Output.StdSemgrepVulsReport'
  - '*.Output.SemgrepVulsReport:=t1.Output.SemgrepVulsReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
