apiVersion: v1alpha1
kind: rule
meta:
  name: AzurePolicyFilteredAndFormattedControlEvidence
  purpose: Azure Policy Filtered And Formatted Control Evidence
  description: Azure Policy Filtered And Formatted Control Evidence
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: AzurePolicyFilterAndFormatRunResult
    alias: t1
    type: task
    purpose: Filter And Format AzurePolicyRunResult
    description: Filter And Format AzurePolicyRunResult
  ioMap:
  - 't1.Input.ControlName:=*.Input.ControlName'
  - 't1.Input.ControlConfigFilePath:=*.Input.ControlConfigFilePath'
  - 't1.Input.AzurePolicyRunResultFilePath:=*.Input.AzurePolicyRunResultFilePath'
  - '*.Output.FilteredAndFormattedControlEvidence:=t1.Output.FilteredAndFormattedControlEvidence'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.LogFile:=t1.Output.LogFile'
