authors:
- sangavi.l@continube.com
domain: continube
createdDate: 13/02/2024
name: AWSAccountAuthorizationDetails
displayName: Fetch AWS Account Authorization Details
version: '1.0'
description: Fetch AWS Account Authorization Details
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: go
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- {}
outputs:
- name: AccountAuthorizationDetails
  description: Account Authorization Details
  type: string
- name: LogFile
  description: Log File
  type: string
- name: CompliancePCT_
  description: Compliance Percentage
  type: int
- name: ComplianceStatus_
  description: Compliance Status
  type: string
