apiVersion: v1alpha1
kind: rule
meta:
  name: AWSMFAReport
  purpose: Generate a compliance report of AWS users mfa details
  description: Aws users MFA details in standard format
  labels:
    app:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    app:
    - aws
spec:
  tasks:
  - name: AWSMFAReport
    alias: t1
    type: task
    purpose: Generate a compliance report of AWS users mfa details
    description: Aws users MFA details in standard format
  ioMap:
  - t1.Input.AWSCredentialReport:=*.Input.AWSCredentialReport
  - '*.Output.AWSMFAReport:=t1.Output.AWSMFAReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'