authors:
- sangavi.l@continube.com
domain: continube
createdDate: 11/12/2023
name: AWSAccessKeyRotationReport
displayName: AWS Access Key Rotation Report
version: '1.0'
description: Generate a compliance report of AWS user access keys based on the provided AccessKeyAge.
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: go
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: MaxAccessKeyAge
  description: Maximum Access Key Age
  type: int
  allowedValues: []
  defaultValue: '90'
  showField: true
  isRequired: true
- name: AWSCredentialReport
  description: AWS Credential Report
  type: string 
  allowedValues: []
  defaultValue: ''
  showField: true
  isRequired: true
outputs:
- name: AccessKeyRotationReport
  description: Access Key Rotation Report
  type: string
- name: LogFile
  description: Log File
  type: string
- name: MetaFile
  description: Meta File
  type: string
- name: CompliancePCT_
  description: Compliance Percentage
  type: int
- name: ComplianceStatus_
  description: Compliance Status
  type: string
