apiVersion: v1alpha1
kind: rule
meta:
  name: AzureServiceBusData
  purpose: AzureServiceBusData
  description: AzureServiceBusData
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: GetAzureServiceBusData  
    alias: t1
    type: task
    purpose: GetAzureServiceBusData 
    description: GetAzureServiceBusData
  ioMap:
  - '*.Output.AzureServiceBusNameSpaces:=t1.Output.AzureServiceBusNameSpaces'
  - '*.Output.ServiceBusNameSpacesDiagnosticSettings:=t1.Output.ServiceBusNameSpacesDiagnosticSettings'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
