apiVersion: v1alpha1
kind: rule
meta:
  name: VerifySessionTokenIsNotPresentInURL
  purpose: Verify session token is not present in URL
  description: Verify session token is not present in URL
  labels:
    appType:
    - nocredapp
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - nocredapp
spec:
  tasks:
  - name: VerifySessionTokenIsNotPresentInURL
    alias: t1
    type: task
    purpose: Verify session token is not present in URL
    description: Verify session token is not present in URL
  ioMap:
  - 't1.Input.HARFile:=*.Input.HARFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.URIsWithTokenInQuery:=t1.Output.URIsWithTokenInQuery'
  - '*.Output.LogFile:=t1.Output.LogFile'
